directories:
  bronze: "Bronze/"
  silver: "Silver/"
  gold: "Gold/"

database:
  connection_string: "mysql+pymysql://root:grill@localhost:3306/earthquake_project"

api:
  primary_url: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson"

pipeline:
  lookback_hours: 24

logging:
  file_name: "pipeline.log"

retry:
  num: 3